import type { AuditEntry, DemoState } from "@/lib/types";

/**
 * Fictional starting records for the demonstration. Organisation names,
 * references, people counts, and budgets are invented. Dates are generated
 * relative to the moment the demo is first opened so due dates stay meaningful.
 *
 * The records marked JOURNEY form the end-to-end walkthrough:
 * partner → intervention → field report → assistance exception → service case → national report.
 */
export const SEED_VERSION = 1;

export const JOURNEY = {
  partnerId: "p-kcha",
  interventionId: "i-0147",
  fieldReportId: "fr-0932",
  exceptionId: "ex-0311",
  caseId: "sc-1184",
  reportId: "nr-2026-q3",
} as const;

const DAY = 24 * 60 * 60 * 1000;

export function createSeed(now = new Date()): DemoState {
  const at = (days: number, hours = 0) => new Date(now.getTime() + days * DAY + hours * 3600 * 1000).toISOString();
  const PREV = "Previous duty coordinator (fictional)";

  let auditId = 0;
  const audit: AuditEntry[] = [];
  const log = (entry: Omit<AuditEntry, "id">) => audit.push({ id: `a-seed-${++auditId}`, ...entry });

  const state: DemoState = {
    version: SEED_VERSION,
    seededAt: now.toISOString(),
    partners: [
      {
        id: JOURNEY.partnerId,
        ref: "PRT-2026-058",
        name: "Kagera Community Health Alliance",
        type: "National NGO",
        registrationNo: "NGO/FIC/2025/0417",
        sectors: ["health"],
        settlementIds: ["nakivale", "kyaka-ii"],
        focalRole: "Programme Director",
        submittedAt: at(-6),
        status: "pending",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "pending" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "pending" },
        ],
        agreement: { status: "not_requested" },
        updatedAt: at(-2),
      },
      {
        id: "p-gli",
        ref: "PRT-2026-061",
        name: "Greenfield Livelihoods Initiative",
        type: "Community-based organisation",
        registrationNo: "CBO/FIC/2026/0122",
        sectors: ["livelihoods"],
        settlementIds: ["kiryandongo"],
        focalRole: "Coordinator",
        submittedAt: at(-3),
        status: "pending",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "missing" },
          { id: "d3", name: "Audited financial statement 2025", status: "pending" },
          { id: "d4", name: "Safeguarding policy", status: "pending" },
        ],
        agreement: { status: "not_requested" },
        updatedAt: at(-3),
      },
      {
        id: "p-lrn",
        ref: "PRT-2024-011",
        name: "Lakeside Relief Network",
        type: "International NGO",
        registrationNo: "INGO/FIC/2019/0033",
        sectors: ["wash", "shelter"],
        settlementIds: ["rhino-camp", "nakivale"],
        focalRole: "Country Director",
        submittedAt: at(-640),
        status: "approved",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Country Director (fictional)", signedAt: at(-600) },
        updatedAt: at(-120),
      },
      {
        id: "p-nvwt",
        ref: "PRT-2024-019",
        name: "Nile Valley Water Trust",
        type: "National NGO",
        registrationNo: "NGO/FIC/2018/0290",
        sectors: ["wash"],
        settlementIds: ["bidibidi", "kiryandongo", "palorinya"],
        focalRole: "Executive Director",
        submittedAt: at(-560),
        status: "approved",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Executive Director (fictional)", signedAt: at(-540) },
        updatedAt: at(-90),
      },
      {
        id: "p-hep",
        ref: "PRT-2025-027",
        name: "Harambee Education Partners",
        type: "International NGO",
        registrationNo: "INGO/FIC/2021/0102",
        sectors: ["education"],
        settlementIds: ["adjumani", "kyaka-ii"],
        focalRole: "Education Programme Lead",
        submittedAt: at(-410),
        status: "approved",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Country Representative (fictional)", signedAt: at(-400) },
        updatedAt: at(-60),
      },
      {
        id: "p-mhs",
        ref: "PRT-2025-033",
        name: "Mwangaza Health Services",
        type: "Faith-based organisation",
        registrationNo: "NGO/FIC/2016/0077",
        sectors: ["health"],
        settlementIds: ["kyangwali", "rwamwanja"],
        focalRole: "Medical Director",
        submittedAt: at(-380),
        status: "approved",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Medical Director (fictional)", signedAt: at(-370) },
        updatedAt: at(-45),
      },
      {
        id: "p-ssp",
        ref: "PRT-2025-040",
        name: "Safe Spaces Protection Forum",
        type: "National NGO",
        registrationNo: "NGO/FIC/2020/0188",
        sectors: ["protection"],
        settlementIds: ["palabek", "kampala"],
        focalRole: "Protection Coordinator",
        submittedAt: at(-300),
        status: "approved",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "verified" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Board Chair (fictional)", signedAt: at(-290) },
        updatedAt: at(-30),
      },
      {
        id: "p-usc",
        ref: "PRT-2025-044",
        name: "Upland Shelter Collective",
        type: "Community-based organisation",
        registrationNo: "CBO/FIC/2022/0310",
        sectors: ["shelter"],
        settlementIds: ["palorinya"],
        focalRole: "Coordinator",
        submittedAt: at(-260),
        status: "suspended",
        documents: [
          { id: "d1", name: "Certificate of registration", status: "verified" },
          { id: "d2", name: "Operating permit", status: "verified" },
          { id: "d3", name: "Audited financial statement 2025", status: "missing" },
          { id: "d4", name: "Safeguarding policy", status: "verified" },
        ],
        agreement: { status: "signed", signedBy: "Coordinator (fictional)", signedAt: at(-250) },
        updatedAt: at(-20),
      },
    ],
    interventions: [
      {
        id: JOURNEY.interventionId,
        ref: "INT-2026-0147",
        title: "Maternal health outreach and dignity kits",
        partnerId: JOURNEY.partnerId,
        sector: "health",
        settlementId: "nakivale",
        startDate: at(-10),
        endDate: at(80),
        budgetUsd: 84500,
        fundingSource: "Pooled response fund (fictional)",
        targetReach: 3200,
        objective:
          "Increase antenatal care attendance through community outreach and provide dignity kits to pregnant and lactating women.",
        activities: [
          "Weekly outreach sessions with community health workers",
          "Distribution of dignity kits at outreach points",
          "Referral of high-risk pregnancies to the health centre",
        ],
        status: "submitted",
        submittedAt: at(-4),
        updatedAt: at(-4),
      },
      {
        id: "i-0152",
        ref: "INT-2026-0152",
        title: "Accelerated learning classes for over-age learners",
        partnerId: "p-hep",
        sector: "education",
        settlementId: "kyaka-ii",
        startDate: at(5),
        endDate: at(185),
        budgetUsd: 126000,
        fundingSource: "Education response grant (fictional)",
        targetReach: 900,
        objective: "Help over-age learners complete primary education in a condensed programme.",
        activities: ["Recruit and train facilitators", "Run accelerated classes in six learning centres"],
        status: "submitted",
        submittedAt: at(-2),
        updatedAt: at(-2),
      },
      {
        id: "i-0098",
        ref: "INT-2026-0098",
        title: "Water point rehabilitation",
        partnerId: "p-nvwt",
        sector: "wash",
        settlementId: "bidibidi",
        startDate: at(-80),
        endDate: at(40),
        budgetUsd: 212000,
        fundingSource: "Bilateral donor grant (fictional)",
        targetReach: 14000,
        objective: "Restore reliable water supply at rehabilitated water points.",
        activities: ["Repair motorised boreholes", "Train water user committees"],
        status: "approved",
        submittedAt: at(-95),
        updatedAt: at(-85),
      },
      {
        id: "i-0104",
        ref: "INT-2026-0104",
        title: "Hygiene promotion campaign",
        partnerId: "p-lrn",
        sector: "wash",
        settlementId: "rhino-camp",
        startDate: at(-70),
        endDate: at(20),
        budgetUsd: 58000,
        fundingSource: "Pooled response fund (fictional)",
        targetReach: 8000,
        objective: "Reduce waterborne illness through hygiene promotion.",
        activities: ["Household hygiene sessions", "Distribution of hygiene kits"],
        status: "approved",
        submittedAt: at(-82),
        updatedAt: at(-75),
      },
      {
        id: "i-0111",
        ref: "INT-2026-0111",
        title: "Primary health care support",
        partnerId: "p-mhs",
        sector: "health",
        settlementId: "kyangwali",
        startDate: at(-60),
        endDate: at(120),
        budgetUsd: 310000,
        fundingSource: "Health response grant (fictional)",
        targetReach: 22000,
        objective: "Maintain outpatient and maternal health services at supported facilities.",
        activities: ["Staff support", "Essential medicines supply"],
        status: "approved",
        submittedAt: at(-70),
        updatedAt: at(-64),
      },
      {
        id: "i-0115",
        ref: "INT-2026-0115",
        title: "Case management for survivors of violence",
        partnerId: "p-ssp",
        sector: "protection",
        settlementId: "palabek",
        startDate: at(-55),
        endDate: at(125),
        budgetUsd: 97000,
        fundingSource: "Protection fund (fictional)",
        targetReach: 600,
        objective: "Provide safe, confidential case management and referrals.",
        activities: ["Case management", "Safe space activities"],
        status: "approved",
        submittedAt: at(-66),
        updatedAt: at(-58),
      },
      {
        id: "i-0120",
        ref: "INT-2026-0120",
        title: "School meals programme",
        partnerId: "p-hep",
        sector: "education",
        settlementId: "adjumani",
        startDate: at(-50),
        endDate: at(130),
        budgetUsd: 145000,
        fundingSource: "Education response grant (fictional)",
        targetReach: 5200,
        objective: "Improve attendance through daily school meals.",
        activities: ["Daily meals in partner schools"],
        status: "approved",
        submittedAt: at(-60),
        updatedAt: at(-52),
      },
      {
        id: "i-0123",
        ref: "INT-2026-0123",
        title: "Borehole drilling",
        partnerId: "p-nvwt",
        sector: "wash",
        settlementId: "kiryandongo",
        startDate: at(-45),
        endDate: at(60),
        budgetUsd: 176000,
        fundingSource: "Bilateral donor grant (fictional)",
        targetReach: 9000,
        objective: "Add new water sources in underserved villages.",
        activities: ["Drill and equip boreholes"],
        status: "approved",
        submittedAt: at(-52),
        updatedAt: at(-47),
      },
      {
        id: "i-0126",
        ref: "INT-2026-0126",
        title: "Sanitation facilities upgrade",
        partnerId: "p-lrn",
        sector: "wash",
        settlementId: "nakivale",
        startDate: at(-40),
        endDate: at(50),
        budgetUsd: 88000,
        fundingSource: "Pooled response fund (fictional)",
        targetReach: 6500,
        objective: "Upgrade shared sanitation facilities.",
        activities: ["Construct latrine blocks", "Hygiene committees"],
        status: "approved",
        submittedAt: at(-48),
        updatedAt: at(-42),
      },
      {
        id: "i-0130",
        ref: "INT-2026-0130",
        title: "Health centre outreach",
        partnerId: "p-mhs",
        sector: "health",
        settlementId: "rwamwanja",
        startDate: at(-35),
        endDate: at(90),
        budgetUsd: 132000,
        fundingSource: "Health response grant (fictional)",
        targetReach: 11000,
        objective: "Extend immunisation and outreach services.",
        activities: ["Mobile clinics", "Immunisation days"],
        status: "approved",
        submittedAt: at(-44),
        updatedAt: at(-38),
      },
      {
        id: "i-0134",
        ref: "INT-2026-0134",
        title: "Urban protection help desk",
        partnerId: "p-ssp",
        sector: "protection",
        settlementId: "kampala",
        startDate: at(-30),
        endDate: at(150),
        budgetUsd: 64000,
        fundingSource: "Protection fund (fictional)",
        targetReach: 1500,
        objective: "Provide information and referrals for urban refugees.",
        activities: ["Help desk operations", "Legal aid referrals"],
        status: "approved",
        submittedAt: at(-38),
        updatedAt: at(-32),
      },
      {
        id: "i-0087",
        ref: "INT-2026-0087",
        title: "Emergency shelter kits",
        partnerId: "p-lrn",
        sector: "shelter",
        settlementId: "rhino-camp",
        startDate: at(-120),
        endDate: at(-15),
        budgetUsd: 72000,
        fundingSource: "Pooled response fund (fictional)",
        targetReach: 2400,
        objective: "Provide shelter kits to newly arrived households.",
        activities: ["Distribute shelter kits"],
        status: "completed",
        submittedAt: at(-130),
        updatedAt: at(-14),
      },
      {
        id: "i-0141",
        ref: "INT-2026-0141",
        title: "Village savings groups",
        partnerId: "p-gli",
        sector: "livelihoods",
        settlementId: "kiryandongo",
        startDate: at(10),
        endDate: at(190),
        budgetUsd: 41000,
        fundingSource: "Livelihoods fund (fictional)",
        targetReach: 750,
        objective: "Establish savings and loan groups.",
        activities: ["Group formation", "Financial literacy training"],
        status: "returned",
        submittedAt: at(-8),
        updatedAt: at(-5),
      },
    ],
    fieldReports: [
      {
        id: JOURNEY.fieldReportId,
        ref: "FR-2026-0932",
        title: "Outreach day and dignity kit distribution",
        interventionId: JOURNEY.interventionId,
        submittedBy: "KCHA outreach team 2 (fictional)",
        channel: "offline",
        activityDate: at(-2),
        receivedAt: at(-1, -3),
        reached: { women: 212, men: 38, children: 164 },
        distributed: [{ item: "Dignity kit", quantity: 180 }],
        narrative:
          "Outreach held at two community points. Kits distributed against the outreach register. Twelve women referred for antenatal follow-up. Submitted from a device without connectivity; synced when the team returned to base.",
        status: "held",
        pendingExceptionIds: [JOURNEY.exceptionId],
        updatedAt: at(-1, -3),
      },
      {
        id: "fr-0901",
        ref: "FR-2026-0901",
        title: "Borehole repairs — batch 3",
        interventionId: "i-0098",
        submittedBy: "NVWT field engineers (fictional)",
        channel: "online",
        activityDate: at(-12),
        receivedAt: at(-11),
        reached: { women: 1450, men: 1320, children: 2210 },
        distributed: [],
        narrative: "Four water points restored to service. Water user committees retrained.",
        status: "accepted",
        pendingExceptionIds: [],
        updatedAt: at(-9),
      },
      {
        id: "fr-0908",
        ref: "FR-2026-0908",
        title: "Hygiene kit distribution",
        interventionId: "i-0104",
        submittedBy: "LRN hygiene promoters (fictional)",
        channel: "offline",
        activityDate: at(-9),
        receivedAt: at(-8),
        reached: { women: 640, men: 410, children: 880 },
        distributed: [{ item: "Hygiene kit", quantity: 520 }],
        narrative: "Kits distributed to households identified in the hygiene survey.",
        status: "accepted",
        pendingExceptionIds: [],
        updatedAt: at(-6),
      },
      {
        id: "fr-0915",
        ref: "FR-2026-0915",
        title: "Outpatient services — monthly summary",
        interventionId: "i-0111",
        submittedBy: "MHS facility team (fictional)",
        channel: "online",
        activityDate: at(-7),
        receivedAt: at(-6),
        reached: { women: 2100, men: 1350, children: 1980 },
        distributed: [],
        narrative: "Monthly outpatient consultations and maternal health visits.",
        status: "accepted",
        pendingExceptionIds: [],
        updatedAt: at(-5),
      },
      {
        id: "fr-0920",
        ref: "FR-2026-0920",
        title: "School meals — term attendance",
        interventionId: "i-0120",
        submittedBy: "HEP school monitors (fictional)",
        channel: "offline",
        activityDate: at(-5),
        receivedAt: at(-4),
        reached: { women: 0, men: 0, children: 4870 },
        distributed: [],
        narrative: "Meals served on all school days in the reporting window.",
        status: "accepted",
        pendingExceptionIds: [],
        updatedAt: at(-3),
      },
      {
        id: "fr-0924",
        ref: "FR-2026-0924",
        title: "Urban help desk — monthly summary",
        interventionId: "i-0134",
        submittedBy: "SSPF help desk (fictional)",
        channel: "online",
        activityDate: at(-4),
        receivedAt: at(-3),
        reached: { women: 190, men: 150, children: 40 },
        distributed: [],
        narrative: "Information sessions and referrals to legal aid providers.",
        status: "accepted",
        pendingExceptionIds: [],
        updatedAt: at(-2),
      },
    ],
    exceptions: [
      {
        id: JOURNEY.exceptionId,
        ref: "AEX-2026-0311",
        fieldReportId: JOURNEY.fieldReportId,
        householdRef: "HH-NKV-••••-72",
        reason: "duplicate",
        detectedAt: at(-1, -3),
        history: [
          { item: "Dignity kit", partnerName: "Lakeside Relief Network", date: at(-14) },
          { item: "Hygiene kit", partnerName: "Lakeside Relief Network", date: at(-40) },
        ],
        verificationSummary:
          "Simulated check: a similar item was recorded for this household reference 12 days before the reported distribution.",
        status: "waiting",
        updatedAt: at(-1, -3),
      },
      {
        id: "ex-0298",
        ref: "AEX-2026-0298",
        fieldReportId: "fr-0908",
        householdRef: "HH-RHC-••••-19",
        reason: "mismatch",
        detectedAt: at(-6),
        history: [{ item: "Hygiene kit", partnerName: "Lakeside Relief Network", date: at(-9) }],
        verificationSummary: "Simulated check: household size recorded differently from registration reference.",
        status: "cleared",
        updatedAt: at(-5),
      },
      {
        id: "ex-0301",
        ref: "AEX-2026-0301",
        fieldReportId: "fr-0908",
        householdRef: "HH-RHC-••••-54",
        reason: "duplicate",
        detectedAt: at(-6),
        history: [
          { item: "Hygiene kit", partnerName: "Lakeside Relief Network", date: at(-9) },
          { item: "Hygiene kit", partnerName: "Lakeside Relief Network", date: at(-9) },
        ],
        verificationSummary: "Simulated check: two identical entries recorded on the same day.",
        status: "duplicate",
        updatedAt: at(-5),
      },
    ],
    cases: [
      {
        id: JOURNEY.caseId,
        ref: "SRV-2026-1184",
        title: "Antenatal care referral follow-up",
        category: "Health referral",
        requesterRef: "RQ-••••-418",
        channel: "Settlement help desk (recorded by staff)",
        settlementId: "nakivale",
        receivedAt: at(-1),
        dueAt: at(2),
        priority: "high",
        summary:
          "Requester asks for follow-up on an antenatal referral made during an outreach session. Needs a partner providing maternal health services in the settlement.",
        status: "new",
        updatedAt: at(-1),
      },
      {
        id: "sc-1179",
        ref: "SRV-2026-1179",
        title: "Water point not working",
        category: "Water and sanitation",
        requesterRef: "RQ-••••-307",
        channel: "Community feedback line (recorded by staff)",
        settlementId: "kiryandongo",
        receivedAt: at(-5),
        dueAt: at(-1),
        priority: "medium",
        summary: "Water point in a village block has not worked for three days.",
        assignedPartnerId: "p-nvwt",
        status: "in_progress",
        updatedAt: at(-3),
      },
      {
        id: "sc-1181",
        ref: "SRV-2026-1181",
        title: "School enrolment support",
        category: "Education",
        requesterRef: "RQ-••••-122",
        channel: "Settlement help desk (recorded by staff)",
        settlementId: "kyaka-ii",
        receivedAt: at(-2),
        dueAt: at(5),
        priority: "medium",
        summary: "Parent requests help enrolling two children who arrived recently.",
        status: "new",
        updatedAt: at(-2),
      },
      {
        id: "sc-1170",
        ref: "SRV-2026-1170",
        title: "Legal aid referral",
        category: "Protection",
        requesterRef: "RQ-••••-061",
        channel: "Urban help desk (recorded by staff)",
        settlementId: "kampala",
        receivedAt: at(-12),
        dueAt: at(-5),
        priority: "medium",
        summary: "Request for referral to a legal aid provider.",
        assignedPartnerId: "p-ssp",
        resolution: "Referred to a legal aid clinic; requester confirmed appointment.",
        status: "resolved",
        updatedAt: at(-6),
      },
      {
        id: "sc-1165",
        ref: "SRV-2026-1165",
        title: "Replacement hygiene kit",
        category: "Water and sanitation",
        requesterRef: "RQ-••••-990",
        channel: "Community feedback line (recorded by staff)",
        settlementId: "rhino-camp",
        receivedAt: at(-18),
        dueAt: at(-11),
        priority: "low",
        summary: "Kit damaged during storage.",
        assignedPartnerId: "p-lrn",
        resolution: "Replacement provided at the next distribution.",
        status: "closed",
        updatedAt: at(-10),
      },
    ],
    reports: [
      {
        id: JOURNEY.reportId,
        ref: "NR-2026-Q3",
        title: "National refugee response report — Q3 2026",
        period: "July–September 2026",
        status: "draft",
        sections: [
          {
            title: "Summary",
            body: "This fictional report summarises reviewed partner activity, field reports, assistance checks, and service cases for the quarter.",
          },
          {
            title: "Coverage",
            body: "Coverage figures are calculated only from approved interventions and accepted field reports.",
          },
          {
            title: "Assistance integrity",
            body: "Flagged assistance records are listed with the coordinator decision recorded for each.",
          },
          {
            title: "Service requests",
            body: "Service cases are reported by status and response time. No requester details are included.",
          },
        ],
        updatedAt: at(-7),
      },
    ],
    integrations: [
      {
        id: "int-exchange",
        ref: "INT-X-04",
        name: "Partner reporting data exchange",
        description: "Shares approved reports and aggregate indicators with authorised partner systems.",
        direction: "Outbound",
        status: "delayed",
        lastSyncAt: at(-1, -2),
        updatedAt: at(0, -1),
      },
      {
        id: "int-registration",
        ref: "INT-X-01",
        name: "Registration reference check",
        description: "Checks household references and assistance history for flagged distributions.",
        direction: "Outbound query",
        status: "healthy",
        lastSyncAt: at(0, -1),
        updatedAt: at(0, -1),
      },
      {
        id: "int-mobile",
        ref: "INT-X-02",
        name: "Mobile field data sync",
        description: "Receives field forms and surveys, including submissions queued offline.",
        direction: "Inbound",
        status: "healthy",
        lastSyncAt: at(0, -1),
        updatedAt: at(0, -1),
      },
      {
        id: "int-sms",
        ref: "INT-X-03",
        name: "SMS and email notifications",
        description: "Sends status notifications to requesters and partners.",
        direction: "Outbound",
        status: "healthy",
        lastSyncAt: at(0, -2),
        updatedAt: at(0, -2),
      },
      {
        id: "int-esign",
        ref: "INT-X-05",
        name: "Electronic signature service",
        description: "Collects signatures on partnership agreements and national reports.",
        direction: "Two-way",
        status: "healthy",
        lastSyncAt: at(0, -3),
        updatedAt: at(0, -3),
      },
    ],
    outbox: [],
    audit,
  };

  // Historical activity so every record has a timeline from the start.
  for (const partner of state.partners) {
    log({ at: partner.submittedAt, actor: null, action: "partnerApplied", params: { name: partner.name }, entity: "partner", entityId: partner.id });
    if (partner.status === "approved" || partner.status === "suspended") {
      log({ at: partner.agreement.signedAt ?? partner.submittedAt, actor: PREV, action: "partnerApproved", params: { name: partner.name }, entity: "partner", entityId: partner.id });
    }
    if (partner.status === "suspended") {
      log({ at: partner.updatedAt, actor: PREV, action: "partnerSuspended", params: { name: partner.name }, entity: "partner", entityId: partner.id, note: "Audited financial statement overdue." });
    }
  }
  for (const item of state.interventions) {
    log({ at: item.submittedAt, actor: null, action: "interventionSubmitted", params: { name: item.ref }, entity: "intervention", entityId: item.id });
    if (item.status === "approved" || item.status === "completed") {
      log({ at: item.updatedAt, actor: PREV, action: "interventionApproved", params: { name: item.ref }, entity: "intervention", entityId: item.id });
    }
    if (item.status === "returned") {
      log({ at: item.updatedAt, actor: PREV, action: "interventionReturned", params: { name: item.ref }, entity: "intervention", entityId: item.id, note: "Partner not yet approved; budget breakdown missing." });
    }
  }
  for (const report of state.fieldReports) {
    log({ at: report.receivedAt, actor: null, action: "fieldReportReceived", params: { name: report.ref }, entity: "fieldReport", entityId: report.id, simulated: true });
    if (report.status === "accepted") {
      log({ at: report.updatedAt, actor: PREV, action: "fieldReportAccepted", params: { name: report.ref }, entity: "fieldReport", entityId: report.id });
    }
  }
  for (const ex of state.exceptions.filter((e) => e.status !== "waiting")) {
    log({ at: ex.detectedAt, actor: null, action: "exceptionOpened", params: { name: ex.ref }, entity: "exception", entityId: ex.id, simulated: true });
    log({
      at: ex.updatedAt,
      actor: PREV,
      action: ex.status === "cleared" ? "exceptionCleared" : "exceptionDuplicate",
      params: { name: ex.ref },
      entity: "exception",
      entityId: ex.id,
    });
  }
  for (const c of state.cases) {
    log({ at: c.receivedAt, actor: PREV, action: "caseReceived", params: { name: c.ref }, entity: "case", entityId: c.id });
  }
  log({ at: at(-7), actor: null, action: "reportDrafted", params: { name: "NR-2026-Q3" }, entity: "report", entityId: JOURNEY.reportId });
  log({ at: at(0, -1), actor: null, action: "integrationDelayed", params: { name: "Partner reporting data exchange" }, entity: "integration", entityId: "int-exchange", simulated: true });

  audit.sort((a, b) => b.at.localeCompare(a.at));
  return state;
}
